### ISSUE TITLE
Forcing content-type keeps returning 'text/plain' always

### ISSUE THREAD

**Issue by jfunez** [idlesign/pytest-responsemock#1]
Hi, 

I'm using:
```
GET http://example.com/foo.jpg
    Content-Type: image/png
    -> 200:
``` 
and appending the bytes of a file.

when asserting the  `response.headers["Content-Type"]` shows: `text/plain, image/png`

how can I get rid of the text/plain?

**Comment by idlesign** [comment]
Hi,

Thank you for the report. I'll see on what goes wrong and what could be done in a week.

**Comment by idlesign** [comment]
1.0.1 is out. Please give it a try.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.

**Comment by jfunez** [comment]
Worked like a charm! 
Thanks a lot!
