### ISSUE TITLE
NameError: name 'response_mock' is not defined

### ISSUE THREAD

**Issue by alex-harvey-z3q** [idlesign/pytest-responsemock#2]
I may be doing something obvious wrong but the docs say, 

> When this package is installed `response_mock` is available for `pytest` test functions.

I'm afraid that isn't happening for me. Instead, I receive a message:

```
    @patch("fx_sceptre.ARTIFACTORY_PATH", "https://github.com/somewhere")
    def test_fetch_zip_file():
>       with response_mock("GET http://github.com -> 200 :Nice"):
E       NameError: name 'response_mock' is not defined
```

Do I need to import it somehow?

**Comment by idlesign** [comment]
The common pattern to use fixture functions in `pytest` is to mention them as parameters, so you need `def test_fetch_zip_file(response_mock):` instead of `def test_fetch_zip_file():`.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
