### ISSUE TITLE
[DOC] explain how to mock mulitple endpoints in the same time in the README examples

### ISSUE THREAD

**Issue by benoitLebreton-perso** [idlesign/pytest-responsemock#3]
Hello ! 
First of all, thanks for this library.
It works very well !

I need to patch multiple endpoints in the same time to test a function and I figured it out by reading your [responsemock/utils.py](https://github.com/idlesign/pytest-responsemock/blob/f32d7824ef82272609cd6ac43ac88b5052866e64/responsemock/utils.py#L31) file so thank you very much.

I think it would be very nice to have this example in your README examples, because I was close to miss it :)

Have a nice day !

**Comment by idlesign** [comment]
Hi.
Thank you. 
I've updated the README.
