### ISSUE TITLE
[Python 3.6] AttributeError: module 're' has no attribute 'Pattern'

### ISSUE THREAD

**Issue by NecroKote** [idlesign/pytest-responsemock#4]
`pytest-responsemock` is dependent on `responses` and it seems like they just dropped support for 3.6 in release `0.18.0`
(https://github.com/getsentry/responses/blob/master/CHANGES)

seems like you need to drop support for 3.6 as well or pin the dependency version to `0.17.0`

(reported from `torrt`\`s PR https://github.com/idlesign/torrt/pull/80)

**Comment by idlesign** [comment]
Thank you. 
I'll try to check this out in a week.

**Comment by idlesign** [comment]
1.1.0 is out with Python 3.7 as a bare minimum.
Considered closed.
