### ISSUE TITLE
responsemock crashed with newest response package

### ISSUE THREAD

**Issue by vansari** [idlesign/pytest-responsemock#5]
Python Version: >=3.6
pytest: 7.0.1
responsemock: latest
ERROR: "ImportError: cannot import name 'UNSET' from 'responses'"

The response package was updated to Version [0.19.0](https://github.com/getsentry/responses/releases/tag/0.19.0) and they have renamed the property UNSET to [_UNSET](https://github.com/getsentry/responses/blob/master/responses/__init__.py#L47).

before I execute my tests now, I must downgrade the response package because the setup installed the latest version.

Please can you fix it or add a version to the package?

**Comment by idlesign** [comment]
Thank you for the report.

Considered closed via https://github.com/idlesign/pytest-responsemock/commit/306be8f00821ec00272d925ec173d457fa34ee02 in  1.1.1. 
Feel free to reopen if required.
